import os
from openai import OpenAI
import json
from typing import Dict, Any


API_KEY = "sk-proj-iJsUrmGG2EjlcGbzhQ63T3BlbkFJilRGJUeOX0ZjbPpWJ2zP"
MODEL = "gpt-4o"


def ai_detector(state: Dict[str, Any]) -> Dict[str, Any]:
    code = state.get("code", "")
    result = {
        "ai_generated_analysis": {},
        "error": None
    }
    
    print("AIDetector state:")
    print(state)
    print("--------------------------------")

    try:
        client = OpenAI(api_key=API_KEY)

        response = client.chat.completions.create(
            model=MODEL,
            response_format={"type": "json_object"},
            messages=[
                {
                    "role": "system",
                    "content": system_prompt()
                },
                {
                    "role": "user",
                    "content": user_prompt(code)
                }
            ]
        )

        output_text = response.choices[0].message.content
        content = json.loads(output_text)

        required_keys = {"ai_generated", "confidence", "reason"}
        if isinstance(content, dict) and required_keys.issubset(content.keys()):
            result["ai_generated_analysis"] = content
        else:
            result["error"] = "Missing keys in response"

    except Exception as e:
        result["error"] = str(e)

    print("AIDetector result:")
    print(result)
    print("--------------------------------")

    return {
        **state,
        "results": {
            **state.get("results", {}),
            "AIDetector": result
        }
    }

def user_prompt(code: str) -> str:
    return f"Analyze the following code and determine if it is likely AI-generated:\n\n{code}"

def system_prompt() -> str:
    return """
You are a programming teaching assistant.
Your task is to evaluate if a given code snippet was likely generated by an AI model (e.g., ChatGPT).
Return your analysis as a **strict JSON** with the following fields:
{
    "ai_generated": true | false,
    "confidence": <0-100>,  // How confident you are it was generated by an AI
    "reason": "<Explain briefly (max 300 chars) why you think it was or wasn't AI-generated. Focus on structure, comments, naming patterns, etc.>"
}
Do not include anything outside the JSON block.
Do not include commentary, markdown, or formatting.
If you're unsure, lean toward human-written (false) with low confidence.
"""
