import os
import json
from typing import Dict, Any, List
from openai import OpenAI


API_KEY = "sk-proj-iJsUrmGG2EjlcGbzhQ63T3BlbkFJilRGJUeOX0ZjbPpWJ2zP"
MODEL = "gpt-4o"
DEFAULT_NODES = ["TestRunner", "PMDRunner", "DesignDetector", "StyleChecker", "AIDetector"]


def router(state: Dict[str, Any]) -> Dict[str, Any]:
    intent = (state.get("intent") or "").strip()
    tests = state.get("tests", None)
    
    print("Router state:")
    print(state)
    print("--------------------------------")

    if not intent:
        # Fallback to default behavior
        return {
            **state,
            "enabled_nodes": DEFAULT_NODES,
            "generate_tests": tests is None
        }

    try:
        client = OpenAI(api_key=API_KEY)

        response = client.chat.completions.create(
            model=MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": system_prompt()},
                {"role": "user", "content": user_prompt(intent, tests)}
            ]
        )
        
        result = json.loads(response.choices[0].message.content)

        print("Router result:")
        print(result)
        print("--------------------------------")

        return {
            **state,
            "enabled_nodes": result.get("enabled_nodes", DEFAULT_NODES),
            "generate_tests": result.get("generate_tests", False),
            "num_tests": result.get("num_tests", None)
        }

    except Exception as e:
        return {
            **state,
            "enabled_nodes": DEFAULT_NODES,
            "generate_tests": tests is None,
            "error": f"Router failed with error: {str(e)}"
        }

def user_prompt(intent: str, tests) -> str:
    return f"""
Given the following user intent: "{intent}",
and the fact that tests {'are missing' if not tests else 'are provided'},
decide what code analysis tasks should be enabled and if tests should be generated or not.
"""

def system_prompt() -> str:
    return """
You are a smart assistant helping to analyze student code.
The user will describe what they want to check (e.g., test the code, detect patterns, check for plagiarism).
Based on that, decide which of the following nodes should be enabled:

- TestRunner - if the user wants to run a set of tests on the code
- DesignDetector - if the user wants to detect design patterns in the code
- PMDRunner - if the user wants to run PMD / static analysis on the code
- StyleChecker - if the user wants to check the code for style / formatting / linting issues
- AIDetector - if the user wants to detect if the code was generated by AI

Also decide whether tests should be generated (generate_tests = true) if the user asks for tests and no tests exist.
If tests are generated, decide how many tests should be generated.

Respond with JSON in this exact format:
{
  "enabled_nodes": [ ... ],
  "generate_tests": true | false,
  "num_tests": <int>
}
Do not add explanations or formatting. Only return valid JSON.
"""
